import Nav from 'components/navBar/nav/Index'
import Head from 'next/head'
import Image from 'next/image'
import styles from 'styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio Gaby</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <h1>Gaby</h1>
        <h2>Full Stack Developer</h2>
        <Nav />
      </header>
      <main className={styles.main}>
        <div className={styles.s}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>
        </div>
        <div>
          <p className={styles.texto}>
            Get started by editing
          </p>
        </div>
      </main >
    </div >
  )
}
